// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("YC.GraphParsingDemo")>]
[<assembly: AssemblyProductAttribute("YC.GraphParsingDemo")>]
[<assembly: AssemblyDescriptionAttribute("Web demo for graph parser")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "YC.GraphParsingDemo"
    let [<Literal>] AssemblyProduct = "YC.GraphParsingDemo"
    let [<Literal>] AssemblyDescription = "Web demo for graph parser"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
